### ISSUE TITLE
Doesn't delete the world after game ends and gives an error

### ISSUE THREAD

**Issue by JonaPoka** [TheSummerGrinch/MCManHunt#24]
I'm getting this error after the game is ended:
(Doesnt delete the world)
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getSpawnLocation()" because the return value of "org.bukkit.Bukkit.getWorld(String)" is null
        at io.github.thesummergrinch.mcmanhunt.game.gamecontrols.Game.lambda$teleportPlayersToDefaultWorld$5(Game.java:452) ~[MCManHunt-1.6.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
        at io.github.thesummergrinch.mcmanhunt.game.gamecontrols.Game.teleportPlayersToDefaultWorld(Game.java:446) ~[MCManHunt-1.6.8.jar:?]
        at io.github.thesummergrinch.mcmanhunt.game.gamecontrols.Game.stop(Game.java:380) ~[MCManHunt-1.6.8.jar:?]
        at io.github.thesummergrinch.mcmanhunt.eventhandlers.OnManHuntWinEventHandler$1.run(OnManHuntWinEventHandler.java:47) ~[MCManHunt-1.6.8.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by TheSummerGrinch** [comment]
Thank you for your report!

I've received similar reports from other Paper users. Unfortunately, as the new academic year has started, I have very little time to work on the plugin. Of course, I will look into it, as soon as I can. However, I cannot guarantee a timeframe.

My apologies for the inconvenience.
